version: '3'
services:
  app:
    container_name: raspberry-pi-container
    restart: always
    build: .
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    ports:
      - '8000:8000'
