version: '3'
services:
  app:
    container_name: raspberry-pi-container
    restart: always
    build: .
    network_mode: "host"
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
    ports:
      - '80:3000'
